os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty

osx_image: xcode9.1
before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew tap vapor/tap;
            brew update;
            brew install vapor;
            brew install vapor/tap/cmysql;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo chmod -R a+rx /usr/;
            sudo apt-get install cmysql;
        fi

script:
    - swift build -DNOJSON
    - swift build -DNOJSON -c release
    - swift test --parallel

after_success:
    - eval "$(curl -sL https://swift.vapor.sh/codecov)"
